name: "🚀 Feature Request"
description: Create a new ticket for a new feature request
title: "🚀 [Feature] - <title>"
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: ✏️ Describe what you expected to happen.
      placeholder: Describe in a few lines or image your feature request.
    validations:
      required: true
  - type: textarea
    id: document_reference
    attributes:
      label: "Document Reference"
      description: 📌 Any other web link related to the feature request.
      placeholder: Pin some links
    validations:
      required: false